---
name: Finalize release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  finalize-release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'automation-create-release') }}
    uses: ./.github/workflows/wf-finalize-release.yaml
    secrets: inherit
    with:
      draft: true
