---
on:
  workflow_call:
    inputs:
      # These inputs are taken directly from stefanzweifel/git-auto-commit-action
      commit_user_name:
        type: string
        description: Name used for the commit user
        required: false
        default: github-actions[bot]
      commit_user_email:
        type: string
        description: Email address used for the commit user
        required: false
        default: 41898282+github-actions[bot]@users.noreply.github.com
    secrets:
      token:
        description: >
          Personal access token (PAT) used to fetch the repository. Required
          if the repository has any private submodules.
        required: false

jobs:
  alias-release:
    runs-on: ubuntu-latest

    steps:
      # Get the version of _this_ repository that is in use so that we can use
      # sidecar scripts
      - id: workflow-parsing
        name: Get SHA of reusuable workflow
        env:
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          GH_TOKEN: ${{ secrets.token || github.token }}
        run: |
          ACTION_DATA=$(gh api "repos/$REPO/actions/runs/$RUN_ID")
          echo "::debug::$ACTION_DATA"
          SHA=$(echo "$ACTION_DATA" | jq -r '.referenced_workflows | .[] | select(.path | startswith("uclahs-cds/tool-create-release")).sha')
          echo "SHA=$SHA" >> "$GITHUB_OUTPUT"

      - name: Checkout reusable repository
        uses: actions/checkout@v4
        with:
          repository: uclahs-cds/tool-create-release
          path: reusable
          ref: ${{ steps.workflow-parsing.outputs.SHA }}

      - name: Checkout calling repository
        uses: actions/checkout@v4
        with:
          path: caller
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.token || github.token }}

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install the bundled package
      - run: pip install ./reusable

      # Update the alias if necessary
      - id: alias-release
        run: |
          git config --file "$REPO_DIR/.git/config" user.name "$COMMIT_USER"
          git config --file "$REPO_DIR/.git/config" user.email "$COMMIT_EMAIL"
          alias-release "$REPO_DIR" "$GITHUB_REF"
        env:
          REPO_DIR: caller
          GH_TOKEN: ${{ secrets.token || github.token }}
          COMMIT_USER: ${{ inputs.commit_user_name }}
          COMMIT_EMAIL: ${{ inputs.commit_user_email }}
